### ISSUE TITLE
'add_extras_bucket' has no effect

### ISSUE THREAD

**Issue by brechtm** [MinoruSekine/setup-scoop#3]
`add_extras_bucket` doesn't seem to have any effect. I tried setting it to `true` and `'true'`:

* https://github.com/brechtm/rinohtype/runs/3782451428?check_suite_focus=true
* https://github.com/brechtm/rinohtype/runs/3782513130?check_suite_focus=true

Thanks for this useful action!

**Comment by MinoruSekine** [comment]
Also I have to apologize late reply by my personal reason 🙇

**Comment by brechtm** [comment]
No problem. As you can see, I'm not very quick in following up myself. 😄 

You can close this ticket. My fork of the action is working well for me (manually adding the extras bucket), so I'll keep using that for now. When I go back to using your version, I'll  open a new ticket here if I run into this again.
