### ISSUE TITLE
Doesn't work invoked from external workflow

### ISSUE THREAD

**Issue by MinoruSekine** [MinoruSekine/setup-scoop#5]
https://github.com/MinoruSekine/dotfiles/pull/132

Log tells latest scoop seems not to work with administrator privilege.

**Comment by RadAd** [comment]
I got this error too. See https://github.com/ScoopInstaller/Install#for-admin

**Comment by MinoruSekine** [comment]
https://github.com/MinoruSekine/setup-scoop/runs/6249443104?check_suite_focus=true

**Comment by MinoruSekine** [comment]
#6 resolves this, and I've confirmed it works on external workflow https://github.com/MinoruSekine/dotfiles/pull/132 .
