### ISSUE TITLE
Release v2.

### ISSUE THREAD

**Issue by MinoruSekine** [MinoruSekine/setup-scoop#7]
# Background
- We need some updates to resolve #5 

# Acceptance criteria
- Update related documents
- Then release v2

**Comment by Integralist** [comment]
👋🏻 is there any update on when v2 is to be released as I'm seeing the earlier reported error:

```
Running the installer as administrator is disabled by default
```

**Comment by MinoruSekine** [comment]
@Integralist Latest main branch has been resolved that, so you can use `@main` instead of `@v1` till `@v2` will be relased. Sorry for inconvenience.

**Comment by MinoruSekine** [comment]
- To do
  1. Complete features for `v2`
  2. Tag `v2`
  3. CI by GitHub Actions for tag `@v2`
  4. Update README.md
